version: '3.6'  
services:
  rabbitmq:
   image: rabbitmq:3-management
   ports:
      # The standard AMQP protocol port
      - '5674:5674'
      # HTTP management UI
      - '15674:15674'
   networks:
      - network
   container_name: rabbitmq
   restart: 'always'

  database:
   image: mongo
   container_name: nestor_mongo
   environment:
      - MONGO_INITDB_DATABASE=nestor
   volumes:
      - ./mongodata:/data/db
   ports:
      - '27020-27020:27020-27020'
      

  nestor_wikipedia_search:
   build:
      context: ./nestor_wikipedia_search
   container_name: nestor_wikipedia_search
   networks:
      - network
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq
   
  nestor_traducir_search:
   build:
      context: ./nestor_traducir_search
   container_name: nestor_traducir_search
   networks:
      - network
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq
  
  nestor_slack_reader:
   build:
     context: ./nestor_slack_reader
   container_name: nestor_slack_reader
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq
   ports:
      - 3000:3000   
   networks:
      - network

  nestor_slack_writer:
   build:
     context: ./nestor_slack_writer
   container_name: nestor_slack_writer
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq   
   networks:
      - network

  nestor_almacena_mensaje:
   build:
      context: ./nestor_almacena_mensaje
   container_name: nestor_almacena_mensaje
   networks:
      - network
   environment:
      - RABBITMQ_HOST=rabbitmq
   depends_on:
      - rabbitmq
networks:
  network: {}
